### ISSUE TITLE
Generated regex doesn't work in VS Code sidebar Search

### ISSUE THREAD

**Issue by i-a-m-d** [usernamehw/vscode-search#1]
The initial regex of your [StackOverflow response](https://stackoverflow.com/a/49944629/3446366) is:
`(word1[\s\S\n]*word2)|(word2[\s\S\n]*word1)`
This regex correctly finds files that contain word1 and word2, in any order.

When using this extension to find a file that contains 2 specific words (in random order), it produces this regex:
`^(?=[\s\S\n]*(word1))(?=[\s\S\n]*(word2))[\s\S\n]*$`
This regex **does not** find any files containing word1 and word2, in any order.

I am using VS Code version 1.54.3 and Search v0.0.1.

**Comment by usernamehw** [comment]
Can't reproduce:

![Screenshot (454)](https://user-images.githubusercontent.com/9638156/111912199-a773eb80-8a79-11eb-864b-3563a4c68aea.png)

**Comment by i-a-m-d** [comment]
You have the files which contain the search terms already open in your editor.
Can you confirm that this regex also works when the respective files are **not** opened?

**Comment by usernamehw** [comment]
![Screenshot (456)](https://user-images.githubusercontent.com/9638156/112262856-60574780-8c7f-11eb-969a-c3003865b214.png)

**Comment by i-a-m-d** [comment]
I am on macOS, are you on Windows? Did you test your extension on macOS sometime?

**Comment by usernamehw** [comment]
Yes, Windows. I don't have a macOS machine.

**Comment by i-a-m-d** [comment]
Thanks for the feedback @usernamehw. I opened a [ticket](https://github.com/microsoft/vscode/issues/119789) in the vscode project and it's now clear why it didn't work. Nothing related to the vscode-search extension, so I'm closing this!
