### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by pcardosow** [usernamehw/vscode-search#2]
Hi, I am a QA developer and i need help with this extension. Basically i need the files where the keywords are present but I don't have any idea how to use this add-in. Can you show a example to how to do this? Please.

,,

**Comment by usernamehw** [comment]
From Command Palette <kbd>F1</kbd> `Find a file that has all provided words`

![Screenshot (120)](https://user-images.githubusercontent.com/9638156/126216587-0c3343fa-2d6d-42b7-8212-4ffa63a75269.png)

Then you input words (separated by 1 whitespace symbol) `one two three`

![Screenshot (122)](https://user-images.githubusercontent.com/9638156/126216648-36344273-ba39-4ff5-b467-a4b92701ca17.png)

**Comment by pcardosow** [comment]
Thank you! I need to filter the paths where these keywords are showed, do you know one way to this? like a Distinct on SQL

An example: 

![image](https://user-images.githubusercontent.com/53201549/126218171-d0fd50a8-877a-4814-91c7-95258a444a73.png)

First occurrence is ok
But I don't wan't two registers of the same path

**Comment by usernamehw** [comment]
Nope. It's a pretty minimalistic extension.

**Comment by pcardosow** [comment]
Do you know another way to do this? 

Anyway, thank you!

**Comment by usernamehw** [comment]
I don't know of any way to do it. You can write a new extension with such features.
